[package]
name = "tarve_native"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
vello = "=0.10.0"
parley = "=0.11.1"
taffy = { version = "=0.14.0", default-features = false, features = ["std", "taffy_tree", "flexbox", "grid", "content_size"] }
winit = "0.30.12"
pollster = "0.4"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
image = { version = "0.25", default-features = false, features = ["png", "jpeg"] }
unicode-segmentation = "1.12"
arboard = { version = "3.6", default-features = false }

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.61.2", features = ["Win32_Foundation", "Win32_Graphics_Dwm", "Win32_Graphics_Gdi"] }
rfd = { version = "=0.17.2", default-features = false, features = ["common-controls-v6"] }

[profile.dev]
opt-level = 1

[profile.release]
lto = "thin"
strip = true
