// Embeds the sample apps as strings for Studio's code tab. The samples stay real,
// typechecked .tsx files; run this after editing one (`--check` fails on drift).
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const directory = import.meta.dirname;
const target = join(directory, "..", "studio-samples.generated.ts");
const names = readdirSync(directory).filter(file => file.endsWith(".tsx")).map(file => file.slice(0, -4)).sort();
const source = [
  "// Generated by studio-samples/generate.ts. Do not edit.",
  "export const previewSources: Record<string, string> = {",
  ...names.map(name => `  ${name}: ${JSON.stringify(readFileSync(join(directory, `${name}.tsx`), "utf8").replace(/\r\n/g, "\n"))},`),
  "};",
  "",
].join("\n");

if (process.argv.includes("--check")) {
  const current = readFileSync(target, "utf8").replace(/\r\n/g, "\n");
  if (current !== source) {
    console.error("studio-samples.generated.ts is stale: run bun studio-samples/generate.ts");
    process.exit(1);
  }
} else {
  writeFileSync(target, source);
}
